# Railway Configuration for VeganFlemme Solver
# Deploy this service to Railway for production solver API

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
# Railway will automatically set PORT
# Add any additional environment variables needed for the solver
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"

# Optional: if the solver needs database access
# DATABASE_URL = "${{Postgres.DATABASE_URL}}"
# SUPABASE_SERVICE_ROLE_KEY = "${{secrets.SUPABASE_SERVICE_ROLE_KEY}}"