name: Solver CI

on:
  push:
    branches: [ main ]
    paths: 
      - 'solver/**'
      - '.github/workflows/solver.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'solver/**'
      - '.github/workflows/solver.yml'

defaults:
  run:
    working-directory: ./solver

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.11, 3.12]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install ruff pytest black
        
    - name: Run ruff linter
      run: ruff check .
      
    - name: Check black formatting
      run: black --check .
      
    - name: Run tests
      run: pytest -v || echo "No tests found, skipping"
      
    - name: Test solver startup
      run: |
        python -c "import uvicorn; from main import app; print('✅ Solver imports successfully')"
        
    - name: Test health endpoint
      run: |
        python -c "
        from main import app
        from fastapi.testclient import TestClient
        client = TestClient(app)
        response = client.get('/health')
        assert response.status_code == 200
        assert response.json()['ok'] == True
        print('✅ Health endpoint works')
        
        response = client.get('/healthz')
        assert response.status_code == 200
        assert response.json()['ok'] == True
        print('✅ Healthz endpoint works')
        "